/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package src;

import javax.swing.JOptionPane;

/**
 *
 * @author alan.ryan
 */
public class ButtonTest extends javax.swing.JFrame {

    /**
     * Creates new form ButtonTest
     */
    public ButtonTest() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        plainButton = new javax.swing.JButton();
        fancyButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Example of Buttons");
        getContentPane().setLayout(new java.awt.BorderLayout(0, 50));

        plainButton.setText("Plain Button");
        plainButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plainButtonActionPerformed(evt);
            }
        });
        getContentPane().add(plainButton, java.awt.BorderLayout.PAGE_START);

        fancyButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/willie.jpg"))); // NOI18N
        fancyButton.setText("Fancy Button");
        fancyButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/moe.jpg"))); // NOI18N
        fancyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fancyButtonActionPerformed(evt);
            }
        });
        getContentPane().add(fancyButton, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void plainButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plainButtonActionPerformed
       JOptionPane.showMessageDialog(null, evt.getActionCommand());
    }//GEN-LAST:event_plainButtonActionPerformed

    private void fancyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fancyButtonActionPerformed
        JOptionPane.showMessageDialog(null, evt.getActionCommand());
    }//GEN-LAST:event_fancyButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ButtonTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ButtonTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ButtonTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ButtonTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new ButtonTest().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton fancyButton;
    private javax.swing.JButton plainButton;
    // End of variables declaration//GEN-END:variables
}
